config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :projects

  get '/projects', to: 'projects#index'
  get '/projects/:id', to: 'projects#show'
  get '/projects/new', to: 'projects#new'
  get '/projects/:id/edit', to: 'projects#edit'
  post '/projects/new', to: 'projects#create'
  delete '/projects/:id', to: 'projects#destroy'
  patch '/projects/:id', to: 'projects#update'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])  
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :create]
  
  def new
    @project = Project.new  # Initialize a new project instance
  end
  
  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted.'
  end

  # ...

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def welcome
  end

  def new
  end
  
  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else 
      render :new
    end
  end

  def show
  end

  def edit
    if !logged_in? || !current_user
      redirect_to root_path
    end
  end
      
  def update
    if @user
      @user.update(user_params)

      if @user.errors.any?
        render "edit"
      else
        redirect_to user_path(@user)
      end
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-4 mb-5">
  <a class="navbar-brand" href="/">MyBaseCamp1</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if !logged_in? %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'New Project', new_project_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Projects', projects_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, method: :delete, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBasecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Include Bootstrap CSS -->
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css' %>
    
    <!-- Include Bootstrap JavaScript -->
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mt-2">
    <%= form.submit "Create Project", class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_with(model: @project, local: true) do |form| %>
  <% if @project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit 'Update Project' %>
  </div>
<% end %>

app/views/projects/index.html.erb
<div class="row mx-3">
  <p style="color: green"><%= notice %></p>

  <h3>Projects</h3>

  <div class="col-md-6" id="projects">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>View</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.description %></td>
          <td><%= button_to 'Show this project', project, method: :get, class: 'btn btn-sm btn-success' %></td>
          <td><%= button_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, class: 'btn btn-small btn-danger' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-6"></div>

  <%= link_to "New project", new_project_path, class: 'text-decoration-none' %>
</div>

app/views/projects/new.html.erb
<div class="row mx-3">
  <h4>New project</h4>

  <div class="col-md-4">
    <%= render "form", project: @project %>

    <br>
    
    <div>
      <%= link_to "Back to projects", projects_path, class: 'text-decoration-none' %>
    </div>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/projects/show.html.erb
<div class="row mx-3">
  <div class="col-md-4">
    <p style="color: green"><%= notice %></p>

    <%= render @project %>
    
    <div>
      <%= link_to "Edit this project", edit_project_path(@project), class: 'text-decoration-none' %> |
      <%= link_to "Back to projects", projects_path, class: 'text-decoration-none' %><br>
    
      <%= button_to "Destroy this project", @project, method: :delete, class: 'btn btn-sm btn-danger' %>
    </div>
  </div>
  <div class="col-md-8">
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="row mx-3">
  <h4>Edit your Account Details</h4>

  <div class="col-md-4">
    <%= form_with model: @user, local: true do |f| %>
      <%= f.label :username %><br>
      <%= f.text_field :username, autofocus: true, class: 'form-control' %><br>

      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %><br>

      <!-- Add an admin checkbox field -->
      <%= f.label :admin, class: 'form-check-label' %>
      <%= f.check_box :admin, class: 'form-check-input' %><br>

      <%= f.submit "Confirm Changes", class: 'btn btn-success btn-small' %>

      <%= link_to "Cancel", user_path(@user), class: 'btn btn-secondary btn-small' %>
    <% end %>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/users/new.html.erb
<div class="row mx-3">
  <h4>Sign Up</h4>

  <div class="col-md-6">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %><br>

      <%= f.label :password %><br>
      <%= f.password_field :password, class: 'form-control' %><br>

      <!-- Add an admin checkbox field -->
      <%= f.label :admin, class: 'form-check-label' %>
      <%= f.check_box :admin, class: 'form-check-input' %><br><br>

      <%= f.submit "Sign Up", class: 'btn btn-success btn-small' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Welcome, <span class="text-success"><%= current_user.username %></span></h1>
      <%= link_to "Edit Account", edit_user_path(current_user), class: 'text-decoration-none' %>
      <%= link_to "Delete Account", current_user, data: { confirm: "Are you sure?" }, method: :delete, class: 'text-decoration-none' %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Would you like to Edit your Account Details?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username, autofocus: true %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit "Confirm Changes" %>
<% end %>